<?php
/**
 * BooksApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API.Bible
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6.3
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Clients\BibleClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use App\Clients\BibleClient\ApiException;
use App\Clients\BibleClient\Configuration;
use App\Clients\BibleClient\HeaderSelector;
use App\Clients\BibleClient\ObjectSerializer;

/**
 * BooksApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BooksApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getAudioBook
     *
     * @param  string $audio_bible_id Id of audio Bible whose Book to fetch (required)
     * @param  string $book_id Id of the Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\InlineResponse2003
     */
    public function getAudioBook($audio_bible_id, $book_id, $include_chapters = null)
    {
        list($response) = $this->getAudioBookWithHttpInfo($audio_bible_id, $book_id, $include_chapters);
        return $response;
    }

    /**
     * Operation getAudioBookWithHttpInfo
     *
     * @param  string $audio_bible_id Id of audio Bible whose Book to fetch (required)
     * @param  string $book_id Id of the Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\InlineResponse2003, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAudioBookWithHttpInfo($audio_bible_id, $book_id, $include_chapters = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse2003';
        $request = $this->getAudioBookRequest($audio_bible_id, $book_id, $include_chapters);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\InlineResponse2003',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAudioBookAsync
     *
     *
     *
     * @param  string $audio_bible_id Id of audio Bible whose Book to fetch (required)
     * @param  string $book_id Id of the Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAudioBookAsync($audio_bible_id, $book_id, $include_chapters = null)
    {
        return $this->getAudioBookAsyncWithHttpInfo($audio_bible_id, $book_id, $include_chapters)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAudioBookAsyncWithHttpInfo
     *
     *
     *
     * @param  string $audio_bible_id Id of audio Bible whose Book to fetch (required)
     * @param  string $book_id Id of the Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAudioBookAsyncWithHttpInfo($audio_bible_id, $book_id, $include_chapters = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse2003';
        $request = $this->getAudioBookRequest($audio_bible_id, $book_id, $include_chapters);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAudioBook'
     *
     * @param  string $audio_bible_id Id of audio Bible whose Book to fetch (required)
     * @param  string $book_id Id of the Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAudioBookRequest($audio_bible_id, $book_id, $include_chapters = null)
    {
        // verify the required parameter 'audio_bible_id' is set
        if ($audio_bible_id === null || (is_array($audio_bible_id) && count($audio_bible_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $audio_bible_id when calling getAudioBook'
            );
        }
        // verify the required parameter 'book_id' is set
        if ($book_id === null || (is_array($book_id) && count($book_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $book_id when calling getAudioBook'
            );
        }

        $resourcePath = '/v1/audio-bibles/{audioBibleId}/books/{bookId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($include_chapters !== null) {
            $queryParams['include-chapters'] = ObjectSerializer::toQueryValue($include_chapters);
        }

        // path params
        if ($audio_bible_id !== null) {
            $resourcePath = str_replace(
                '{' . 'audioBibleId' . '}',
                ObjectSerializer::toPathValue($audio_bible_id),
                $resourcePath
            );
        }
        // path params
        if ($book_id !== null) {
            $resourcePath = str_replace(
                '{' . 'bookId' . '}',
                ObjectSerializer::toPathValue($book_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $headers['api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAudioBooks
     *
     * @param  string $audio_bible_id Id of audio Bible whose Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     * @param  bool $include_chapters_and_sections Boolean indicating if an array of chapter summaries and an array of sections should be included in the results. Defaults to false. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\InlineResponse2002
     */
    public function getAudioBooks($audio_bible_id, $include_chapters = null, $include_chapters_and_sections = null)
    {
        list($response) = $this->getAudioBooksWithHttpInfo($audio_bible_id, $include_chapters, $include_chapters_and_sections);
        return $response;
    }

    /**
     * Operation getAudioBooksWithHttpInfo
     *
     * @param  string $audio_bible_id Id of audio Bible whose Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     * @param  bool $include_chapters_and_sections Boolean indicating if an array of chapter summaries and an array of sections should be included in the results. Defaults to false. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\InlineResponse2002, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAudioBooksWithHttpInfo($audio_bible_id, $include_chapters = null, $include_chapters_and_sections = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse2002';
        $request = $this->getAudioBooksRequest($audio_bible_id, $include_chapters, $include_chapters_and_sections);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\InlineResponse2002',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAudioBooksAsync
     *
     *
     *
     * @param  string $audio_bible_id Id of audio Bible whose Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     * @param  bool $include_chapters_and_sections Boolean indicating if an array of chapter summaries and an array of sections should be included in the results. Defaults to false. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAudioBooksAsync($audio_bible_id, $include_chapters = null, $include_chapters_and_sections = null)
    {
        return $this->getAudioBooksAsyncWithHttpInfo($audio_bible_id, $include_chapters, $include_chapters_and_sections)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAudioBooksAsyncWithHttpInfo
     *
     *
     *
     * @param  string $audio_bible_id Id of audio Bible whose Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     * @param  bool $include_chapters_and_sections Boolean indicating if an array of chapter summaries and an array of sections should be included in the results. Defaults to false. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAudioBooksAsyncWithHttpInfo($audio_bible_id, $include_chapters = null, $include_chapters_and_sections = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse2002';
        $request = $this->getAudioBooksRequest($audio_bible_id, $include_chapters, $include_chapters_and_sections);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAudioBooks'
     *
     * @param  string $audio_bible_id Id of audio Bible whose Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     * @param  bool $include_chapters_and_sections Boolean indicating if an array of chapter summaries and an array of sections should be included in the results. Defaults to false. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAudioBooksRequest($audio_bible_id, $include_chapters = null, $include_chapters_and_sections = null)
    {
        // verify the required parameter 'audio_bible_id' is set
        if ($audio_bible_id === null || (is_array($audio_bible_id) && count($audio_bible_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $audio_bible_id when calling getAudioBooks'
            );
        }

        $resourcePath = '/v1/audio-bibles/{audioBibleId}/books';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($include_chapters !== null) {
            $queryParams['include-chapters'] = ObjectSerializer::toQueryValue($include_chapters);
        }
        // query params
        if ($include_chapters_and_sections !== null) {
            $queryParams['include-chapters-and-sections'] = ObjectSerializer::toQueryValue($include_chapters_and_sections);
        }

        // path params
        if ($audio_bible_id !== null) {
            $resourcePath = str_replace(
                '{' . 'audioBibleId' . '}',
                ObjectSerializer::toPathValue($audio_bible_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $headers['api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBook
     *
     * @param  string $bible_id Id of Bible whose Book to fetch (required)
     * @param  string $book_id Id of the Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\InlineResponse2003
     */
    public function getBook($bible_id, $book_id, $include_chapters = null)
    {
        list($response) = $this->getBookWithHttpInfo($bible_id, $book_id, $include_chapters);
        return $response;
    }

    /**
     * Operation getBookWithHttpInfo
     *
     * @param  string $bible_id Id of Bible whose Book to fetch (required)
     * @param  string $book_id Id of the Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\InlineResponse2003, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBookWithHttpInfo($bible_id, $book_id, $include_chapters = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse2003';
        $request = $this->getBookRequest($bible_id, $book_id, $include_chapters);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\InlineResponse2003',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBookAsync
     *
     *
     *
     * @param  string $bible_id Id of Bible whose Book to fetch (required)
     * @param  string $book_id Id of the Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBookAsync($bible_id, $book_id, $include_chapters = null)
    {
        return $this->getBookAsyncWithHttpInfo($bible_id, $book_id, $include_chapters)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBookAsyncWithHttpInfo
     *
     *
     *
     * @param  string $bible_id Id of Bible whose Book to fetch (required)
     * @param  string $book_id Id of the Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBookAsyncWithHttpInfo($bible_id, $book_id, $include_chapters = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse2003';
        $request = $this->getBookRequest($bible_id, $book_id, $include_chapters);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBook'
     *
     * @param  string $bible_id Id of Bible whose Book to fetch (required)
     * @param  string $book_id Id of the Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getBookRequest($bible_id, $book_id, $include_chapters = null)
    {
        // verify the required parameter 'bible_id' is set
        if ($bible_id === null || (is_array($bible_id) && count($bible_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bible_id when calling getBook'
            );
        }
        // verify the required parameter 'book_id' is set
        if ($book_id === null || (is_array($book_id) && count($book_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $book_id when calling getBook'
            );
        }

        $resourcePath = '/v1/bibles/{bibleId}/books/{bookId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($include_chapters !== null) {
            $queryParams['include-chapters'] = ObjectSerializer::toQueryValue($include_chapters);
        }

        // path params
        if ($bible_id !== null) {
            $resourcePath = str_replace(
                '{' . 'bibleId' . '}',
                ObjectSerializer::toPathValue($bible_id),
                $resourcePath
            );
        }
        // path params
        if ($book_id !== null) {
            $resourcePath = str_replace(
                '{' . 'bookId' . '}',
                ObjectSerializer::toPathValue($book_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $headers['api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBooks
     *
     * @param  string $bible_id Id of Bible whose Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     * @param  bool $include_chapters_and_sections Boolean indicating if an array of chapter summaries and an array of sections should be included in the results. Defaults to false. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\InlineResponse2002
     */
    public function getBooks($bible_id, $include_chapters = null, $include_chapters_and_sections = null)
    {
        list($response) = $this->getBooksWithHttpInfo($bible_id, $include_chapters, $include_chapters_and_sections);
        return $response;
    }

    /**
     * Operation getBooksWithHttpInfo
     *
     * @param  string $bible_id Id of Bible whose Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     * @param  bool $include_chapters_and_sections Boolean indicating if an array of chapter summaries and an array of sections should be included in the results. Defaults to false. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\InlineResponse2002, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBooksWithHttpInfo($bible_id, $include_chapters = null, $include_chapters_and_sections = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse2002';
        $request = $this->getBooksRequest($bible_id, $include_chapters, $include_chapters_and_sections);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\InlineResponse2002',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBooksAsync
     *
     *
     *
     * @param  string $bible_id Id of Bible whose Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     * @param  bool $include_chapters_and_sections Boolean indicating if an array of chapter summaries and an array of sections should be included in the results. Defaults to false. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBooksAsync($bible_id, $include_chapters = null, $include_chapters_and_sections = null)
    {
        return $this->getBooksAsyncWithHttpInfo($bible_id, $include_chapters, $include_chapters_and_sections)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBooksAsyncWithHttpInfo
     *
     *
     *
     * @param  string $bible_id Id of Bible whose Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     * @param  bool $include_chapters_and_sections Boolean indicating if an array of chapter summaries and an array of sections should be included in the results. Defaults to false. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBooksAsyncWithHttpInfo($bible_id, $include_chapters = null, $include_chapters_and_sections = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse2002';
        $request = $this->getBooksRequest($bible_id, $include_chapters, $include_chapters_and_sections);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBooks'
     *
     * @param  string $bible_id Id of Bible whose Book to fetch (required)
     * @param  bool $include_chapters Boolean indicating if an array of chapter summaries should be included in the results. Defaults to false. (optional)
     * @param  bool $include_chapters_and_sections Boolean indicating if an array of chapter summaries and an array of sections should be included in the results. Defaults to false. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getBooksRequest($bible_id, $include_chapters = null, $include_chapters_and_sections = null)
    {
        // verify the required parameter 'bible_id' is set
        if ($bible_id === null || (is_array($bible_id) && count($bible_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bible_id when calling getBooks'
            );
        }

        $resourcePath = '/v1/bibles/{bibleId}/books';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($include_chapters !== null) {
            $queryParams['include-chapters'] = ObjectSerializer::toQueryValue($include_chapters);
        }
        // query params
        if ($include_chapters_and_sections !== null) {
            $queryParams['include-chapters-and-sections'] = ObjectSerializer::toQueryValue($include_chapters_and_sections);
        }

        // path params
        if ($bible_id !== null) {
            $resourcePath = str_replace(
                '{' . 'bibleId' . '}',
                ObjectSerializer::toPathValue($bible_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $headers['api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
