<?php
/**
 * SectionsApi
 * PHP version 5
 *
 * @category Class
 * @package  App\Clients\BibleClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API.Bible
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6.3
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Clients\BibleClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use App\Clients\BibleClient\ApiException;
use App\Clients\BibleClient\Configuration;
use App\Clients\BibleClient\HeaderSelector;
use App\Clients\BibleClient\ObjectSerializer;

/**
 * SectionsApi Class Doc Comment
 *
 * @category Class
 * @package  App\Clients\BibleClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SectionsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getBookSections
     *
     * @param  string $bible_id Id of Bible whose Sections to fetch (required)
     * @param  string $book_id Id of the Book whose Sections to fetch (required)
     *
     * @throws \App\Clients\BibleClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \App\Clients\BibleClient\Model\InlineResponse2007
     */
    public function getBookSections($bible_id, $book_id)
    {
        list($response) = $this->getBookSectionsWithHttpInfo($bible_id, $book_id);
        return $response;
    }

    /**
     * Operation getBookSectionsWithHttpInfo
     *
     * @param  string $bible_id Id of Bible whose Sections to fetch (required)
     * @param  string $book_id Id of the Book whose Sections to fetch (required)
     *
     * @throws \App\Clients\BibleClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \App\Clients\BibleClient\Model\InlineResponse2007, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBookSectionsWithHttpInfo($bible_id, $book_id)
    {
        $returnType = '\App\Clients\BibleClient\Model\InlineResponse2007';
        $request = $this->getBookSectionsRequest($bible_id, $book_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\Clients\BibleClient\Model\InlineResponse2007',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBookSectionsAsync
     *
     *
     *
     * @param  string $bible_id Id of Bible whose Sections to fetch (required)
     * @param  string $book_id Id of the Book whose Sections to fetch (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBookSectionsAsync($bible_id, $book_id)
    {
        return $this->getBookSectionsAsyncWithHttpInfo($bible_id, $book_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBookSectionsAsyncWithHttpInfo
     *
     *
     *
     * @param  string $bible_id Id of Bible whose Sections to fetch (required)
     * @param  string $book_id Id of the Book whose Sections to fetch (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBookSectionsAsyncWithHttpInfo($bible_id, $book_id)
    {
        $returnType = '\App\Clients\BibleClient\Model\InlineResponse2007';
        $request = $this->getBookSectionsRequest($bible_id, $book_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBookSections'
     *
     * @param  string $bible_id Id of Bible whose Sections to fetch (required)
     * @param  string $book_id Id of the Book whose Sections to fetch (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getBookSectionsRequest($bible_id, $book_id)
    {
        // verify the required parameter 'bible_id' is set
        if ($bible_id === null || (is_array($bible_id) && count($bible_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bible_id when calling getBookSections'
            );
        }
        // verify the required parameter 'book_id' is set
        if ($book_id === null || (is_array($book_id) && count($book_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $book_id when calling getBookSections'
            );
        }

        $resourcePath = '/v1/bibles/{bibleId}/books/{bookId}/sections';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($bible_id !== null) {
            $resourcePath = str_replace(
                '{' . 'bibleId' . '}',
                ObjectSerializer::toPathValue($bible_id),
                $resourcePath
            );
        }
        // path params
        if ($book_id !== null) {
            $resourcePath = str_replace(
                '{' . 'bookId' . '}',
                ObjectSerializer::toPathValue($book_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $headers['api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getChapterSections
     *
     * @param  string $bible_id Id of Bible whose Sections to fetch (required)
     * @param  string $chapter_id Id of the Chapter whose Sections to fetch (required)
     *
     * @throws \App\Clients\BibleClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \App\Clients\BibleClient\Model\InlineResponse2007
     */
    public function getChapterSections($bible_id, $chapter_id)
    {
        list($response) = $this->getChapterSectionsWithHttpInfo($bible_id, $chapter_id);
        return $response;
    }

    /**
     * Operation getChapterSectionsWithHttpInfo
     *
     * @param  string $bible_id Id of Bible whose Sections to fetch (required)
     * @param  string $chapter_id Id of the Chapter whose Sections to fetch (required)
     *
     * @throws \App\Clients\BibleClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \App\Clients\BibleClient\Model\InlineResponse2007, HTTP status code, HTTP response headers (array of strings)
     */
    public function getChapterSectionsWithHttpInfo($bible_id, $chapter_id)
    {
        $returnType = '\App\Clients\BibleClient\Model\InlineResponse2007';
        $request = $this->getChapterSectionsRequest($bible_id, $chapter_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\Clients\BibleClient\Model\InlineResponse2007',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getChapterSectionsAsync
     *
     *
     *
     * @param  string $bible_id Id of Bible whose Sections to fetch (required)
     * @param  string $chapter_id Id of the Chapter whose Sections to fetch (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getChapterSectionsAsync($bible_id, $chapter_id)
    {
        return $this->getChapterSectionsAsyncWithHttpInfo($bible_id, $chapter_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getChapterSectionsAsyncWithHttpInfo
     *
     *
     *
     * @param  string $bible_id Id of Bible whose Sections to fetch (required)
     * @param  string $chapter_id Id of the Chapter whose Sections to fetch (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getChapterSectionsAsyncWithHttpInfo($bible_id, $chapter_id)
    {
        $returnType = '\App\Clients\BibleClient\Model\InlineResponse2007';
        $request = $this->getChapterSectionsRequest($bible_id, $chapter_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getChapterSections'
     *
     * @param  string $bible_id Id of Bible whose Sections to fetch (required)
     * @param  string $chapter_id Id of the Chapter whose Sections to fetch (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getChapterSectionsRequest($bible_id, $chapter_id)
    {
        // verify the required parameter 'bible_id' is set
        if ($bible_id === null || (is_array($bible_id) && count($bible_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bible_id when calling getChapterSections'
            );
        }
        // verify the required parameter 'chapter_id' is set
        if ($chapter_id === null || (is_array($chapter_id) && count($chapter_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chapter_id when calling getChapterSections'
            );
        }

        $resourcePath = '/v1/bibles/{bibleId}/chapters/{chapterId}/sections';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($bible_id !== null) {
            $resourcePath = str_replace(
                '{' . 'bibleId' . '}',
                ObjectSerializer::toPathValue($bible_id),
                $resourcePath
            );
        }
        // path params
        if ($chapter_id !== null) {
            $resourcePath = str_replace(
                '{' . 'chapterId' . '}',
                ObjectSerializer::toPathValue($chapter_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $headers['api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSection
     *
     * @param  string $bible_id Id of Bible whose Section to fetch (required)
     * @param  string $section_id Id of the Section to fetch (required)
     * @param  string $content_type Content type to be returned in the content property.  Supported values are &#x60;html&#x60; (default), &#x60;json&#x60; (beta), and &#x60;text&#x60; (beta) (optional, default to html)
     * @param  bool $include_notes Include footnotes in content (optional, default to false)
     * @param  bool $include_titles Include section titles in content (optional, default to true)
     * @param  bool $include_chapter_numbers Include chapter numbers in content (optional, default to false)
     * @param  bool $include_verse_numbers Include verse numbers in content. (optional, default to true)
     * @param  bool $include_verse_spans Include spans that wrap verse numbers and verse text for bible content. (optional, default to false)
     * @param  string $parallels Comma delimited list of bibleIds to include (optional)
     *
     * @throws \App\Clients\BibleClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \App\Clients\BibleClient\Model\InlineResponse2008
     */
    public function getSection($bible_id, $section_id, $content_type = 'html', $include_notes = 'false', $include_titles = 'true', $include_chapter_numbers = 'false', $include_verse_numbers = 'true', $include_verse_spans = 'false', $parallels = null)
    {
        list($response) = $this->getSectionWithHttpInfo($bible_id, $section_id, $content_type, $include_notes, $include_titles, $include_chapter_numbers, $include_verse_numbers, $include_verse_spans, $parallels);
        return $response;
    }

    /**
     * Operation getSectionWithHttpInfo
     *
     * @param  string $bible_id Id of Bible whose Section to fetch (required)
     * @param  string $section_id Id of the Section to fetch (required)
     * @param  string $content_type Content type to be returned in the content property.  Supported values are &#x60;html&#x60; (default), &#x60;json&#x60; (beta), and &#x60;text&#x60; (beta) (optional, default to html)
     * @param  bool $include_notes Include footnotes in content (optional, default to false)
     * @param  bool $include_titles Include section titles in content (optional, default to true)
     * @param  bool $include_chapter_numbers Include chapter numbers in content (optional, default to false)
     * @param  bool $include_verse_numbers Include verse numbers in content. (optional, default to true)
     * @param  bool $include_verse_spans Include spans that wrap verse numbers and verse text for bible content. (optional, default to false)
     * @param  string $parallels Comma delimited list of bibleIds to include (optional)
     *
     * @throws \App\Clients\BibleClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \App\Clients\BibleClient\Model\InlineResponse2008, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSectionWithHttpInfo($bible_id, $section_id, $content_type = 'html', $include_notes = 'false', $include_titles = 'true', $include_chapter_numbers = 'false', $include_verse_numbers = 'true', $include_verse_spans = 'false', $parallels = null)
    {
        $returnType = '\App\Clients\BibleClient\Model\InlineResponse2008';
        $request = $this->getSectionRequest($bible_id, $section_id, $content_type, $include_notes, $include_titles, $include_chapter_numbers, $include_verse_numbers, $include_verse_spans, $parallels);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\Clients\BibleClient\Model\InlineResponse2008',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSectionAsync
     *
     *
     *
     * @param  string $bible_id Id of Bible whose Section to fetch (required)
     * @param  string $section_id Id of the Section to fetch (required)
     * @param  string $content_type Content type to be returned in the content property.  Supported values are &#x60;html&#x60; (default), &#x60;json&#x60; (beta), and &#x60;text&#x60; (beta) (optional, default to html)
     * @param  bool $include_notes Include footnotes in content (optional, default to false)
     * @param  bool $include_titles Include section titles in content (optional, default to true)
     * @param  bool $include_chapter_numbers Include chapter numbers in content (optional, default to false)
     * @param  bool $include_verse_numbers Include verse numbers in content. (optional, default to true)
     * @param  bool $include_verse_spans Include spans that wrap verse numbers and verse text for bible content. (optional, default to false)
     * @param  string $parallels Comma delimited list of bibleIds to include (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSectionAsync($bible_id, $section_id, $content_type = 'html', $include_notes = 'false', $include_titles = 'true', $include_chapter_numbers = 'false', $include_verse_numbers = 'true', $include_verse_spans = 'false', $parallels = null)
    {
        return $this->getSectionAsyncWithHttpInfo($bible_id, $section_id, $content_type, $include_notes, $include_titles, $include_chapter_numbers, $include_verse_numbers, $include_verse_spans, $parallels)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSectionAsyncWithHttpInfo
     *
     *
     *
     * @param  string $bible_id Id of Bible whose Section to fetch (required)
     * @param  string $section_id Id of the Section to fetch (required)
     * @param  string $content_type Content type to be returned in the content property.  Supported values are &#x60;html&#x60; (default), &#x60;json&#x60; (beta), and &#x60;text&#x60; (beta) (optional, default to html)
     * @param  bool $include_notes Include footnotes in content (optional, default to false)
     * @param  bool $include_titles Include section titles in content (optional, default to true)
     * @param  bool $include_chapter_numbers Include chapter numbers in content (optional, default to false)
     * @param  bool $include_verse_numbers Include verse numbers in content. (optional, default to true)
     * @param  bool $include_verse_spans Include spans that wrap verse numbers and verse text for bible content. (optional, default to false)
     * @param  string $parallels Comma delimited list of bibleIds to include (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSectionAsyncWithHttpInfo($bible_id, $section_id, $content_type = 'html', $include_notes = 'false', $include_titles = 'true', $include_chapter_numbers = 'false', $include_verse_numbers = 'true', $include_verse_spans = 'false', $parallels = null)
    {
        $returnType = '\App\Clients\BibleClient\Model\InlineResponse2008';
        $request = $this->getSectionRequest($bible_id, $section_id, $content_type, $include_notes, $include_titles, $include_chapter_numbers, $include_verse_numbers, $include_verse_spans, $parallels);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSection'
     *
     * @param  string $bible_id Id of Bible whose Section to fetch (required)
     * @param  string $section_id Id of the Section to fetch (required)
     * @param  string $content_type Content type to be returned in the content property.  Supported values are &#x60;html&#x60; (default), &#x60;json&#x60; (beta), and &#x60;text&#x60; (beta) (optional, default to html)
     * @param  bool $include_notes Include footnotes in content (optional, default to false)
     * @param  bool $include_titles Include section titles in content (optional, default to true)
     * @param  bool $include_chapter_numbers Include chapter numbers in content (optional, default to false)
     * @param  bool $include_verse_numbers Include verse numbers in content. (optional, default to true)
     * @param  bool $include_verse_spans Include spans that wrap verse numbers and verse text for bible content. (optional, default to false)
     * @param  string $parallels Comma delimited list of bibleIds to include (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSectionRequest($bible_id, $section_id, $content_type = 'html', $include_notes = 'false', $include_titles = 'true', $include_chapter_numbers = 'false', $include_verse_numbers = 'true', $include_verse_spans = 'false', $parallels = null)
    {
        // verify the required parameter 'bible_id' is set
        if ($bible_id === null || (is_array($bible_id) && count($bible_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bible_id when calling getSection'
            );
        }
        // verify the required parameter 'section_id' is set
        if ($section_id === null || (is_array($section_id) && count($section_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $section_id when calling getSection'
            );
        }

        $resourcePath = '/v1/bibles/{bibleId}/sections/{sectionId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($content_type !== null) {
            $queryParams['content-type'] = ObjectSerializer::toQueryValue($content_type);
        }
        // query params
        if ($include_notes !== null) {
            $queryParams['include-notes'] = ObjectSerializer::toQueryValue($include_notes);
        }
        // query params
        if ($include_titles !== null) {
            $queryParams['include-titles'] = ObjectSerializer::toQueryValue($include_titles);
        }
        // query params
        if ($include_chapter_numbers !== null) {
            $queryParams['include-chapter-numbers'] = ObjectSerializer::toQueryValue($include_chapter_numbers);
        }
        // query params
        if ($include_verse_numbers !== null) {
            $queryParams['include-verse-numbers'] = ObjectSerializer::toQueryValue($include_verse_numbers);
        }
        // query params
        if ($include_verse_spans !== null) {
            $queryParams['include-verse-spans'] = ObjectSerializer::toQueryValue($include_verse_spans);
        }
        // query params
        if ($parallels !== null) {
            $queryParams['parallels'] = ObjectSerializer::toQueryValue($parallels);
        }

        // path params
        if ($bible_id !== null) {
            $resourcePath = str_replace(
                '{' . 'bibleId' . '}',
                ObjectSerializer::toPathValue($bible_id),
                $resourcePath
            );
        }
        // path params
        if ($section_id !== null) {
            $resourcePath = str_replace(
                '{' . 'sectionId' . '}',
                ObjectSerializer::toPathValue($section_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $headers['api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
