<?php
/**
 * VersesApi
 * PHP version 5
 *
 * @category Class
 * @package  App\Clients\BibleClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API.Bible
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6.3
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Clients\BibleClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use App\Clients\BibleClient\ApiException;
use App\Clients\BibleClient\Configuration;
use App\Clients\BibleClient\HeaderSelector;
use App\Clients\BibleClient\ObjectSerializer;

/**
 * VersesApi Class Doc Comment
 *
 * @category Class
 * @package  App\Clients\BibleClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VersesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getVerse
     *
     * @param  string $bible_id Id of Bible for passage (required)
     * @param  string $verse_id String reference id for the requested verse. (required)
     * @param  string $content_type Content type to be returned in the content property.  Supported values are &#x60;html&#x60; (default), &#x60;json&#x60; (beta), and &#x60;text&#x60; (beta) (optional, default to html)
     * @param  bool $include_notes Include footnotes in content (optional, default to false)
     * @param  bool $include_titles Include section titles in content (optional, default to true)
     * @param  bool $include_chapter_numbers Include chapter numbers in content (optional, default to false)
     * @param  bool $include_verse_numbers Include verse numbers in content. (optional, default to true)
     * @param  bool $include_verse_spans Include spans that wrap verse numbers and verse text for bible content. (optional, default to false)
     * @param  string $parallels Comma delimited list of bibleIds to include (optional)
     * @param  bool $use_org_id Use the supplied id(s) to match the verseOrgId instead of the verseId (optional, default to false)
     *
     * @throws \App\Clients\BibleClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \App\Clients\BibleClient\Model\InlineResponse20010
     */
    public function getVerse($bible_id, $verse_id, $content_type = 'html', $include_notes = 'false', $include_titles = 'true', $include_chapter_numbers = 'false', $include_verse_numbers = 'true', $include_verse_spans = 'false', $parallels = null, $use_org_id = 'false')
    {
        list($response) = $this->getVerseWithHttpInfo($bible_id, $verse_id, $content_type, $include_notes, $include_titles, $include_chapter_numbers, $include_verse_numbers, $include_verse_spans, $parallels, $use_org_id);
        return $response;
    }

    /**
     * Operation getVerseWithHttpInfo
     *
     * @param  string $bible_id Id of Bible for passage (required)
     * @param  string $verse_id String reference id for the requested verse. (required)
     * @param  string $content_type Content type to be returned in the content property.  Supported values are &#x60;html&#x60; (default), &#x60;json&#x60; (beta), and &#x60;text&#x60; (beta) (optional, default to html)
     * @param  bool $include_notes Include footnotes in content (optional, default to false)
     * @param  bool $include_titles Include section titles in content (optional, default to true)
     * @param  bool $include_chapter_numbers Include chapter numbers in content (optional, default to false)
     * @param  bool $include_verse_numbers Include verse numbers in content. (optional, default to true)
     * @param  bool $include_verse_spans Include spans that wrap verse numbers and verse text for bible content. (optional, default to false)
     * @param  string $parallels Comma delimited list of bibleIds to include (optional)
     * @param  bool $use_org_id Use the supplied id(s) to match the verseOrgId instead of the verseId (optional, default to false)
     *
     * @throws \App\Clients\BibleClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \App\Clients\BibleClient\Model\InlineResponse20010, HTTP status code, HTTP response headers (array of strings)
     */
    public function getVerseWithHttpInfo($bible_id, $verse_id, $content_type = 'html', $include_notes = 'false', $include_titles = 'true', $include_chapter_numbers = 'false', $include_verse_numbers = 'true', $include_verse_spans = 'false', $parallels = null, $use_org_id = 'false')
    {
        $returnType = '\App\Clients\BibleClient\Model\InlineResponse20010';
        $request = $this->getVerseRequest($bible_id, $verse_id, $content_type, $include_notes, $include_titles, $include_chapter_numbers, $include_verse_numbers, $include_verse_spans, $parallels, $use_org_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\Clients\BibleClient\Model\InlineResponse20010',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getVerseAsync
     *
     *
     *
     * @param  string $bible_id Id of Bible for passage (required)
     * @param  string $verse_id String reference id for the requested verse. (required)
     * @param  string $content_type Content type to be returned in the content property.  Supported values are &#x60;html&#x60; (default), &#x60;json&#x60; (beta), and &#x60;text&#x60; (beta) (optional, default to html)
     * @param  bool $include_notes Include footnotes in content (optional, default to false)
     * @param  bool $include_titles Include section titles in content (optional, default to true)
     * @param  bool $include_chapter_numbers Include chapter numbers in content (optional, default to false)
     * @param  bool $include_verse_numbers Include verse numbers in content. (optional, default to true)
     * @param  bool $include_verse_spans Include spans that wrap verse numbers and verse text for bible content. (optional, default to false)
     * @param  string $parallels Comma delimited list of bibleIds to include (optional)
     * @param  bool $use_org_id Use the supplied id(s) to match the verseOrgId instead of the verseId (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVerseAsync($bible_id, $verse_id, $content_type = 'html', $include_notes = 'false', $include_titles = 'true', $include_chapter_numbers = 'false', $include_verse_numbers = 'true', $include_verse_spans = 'false', $parallels = null, $use_org_id = 'false')
    {
        return $this->getVerseAsyncWithHttpInfo($bible_id, $verse_id, $content_type, $include_notes, $include_titles, $include_chapter_numbers, $include_verse_numbers, $include_verse_spans, $parallels, $use_org_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getVerseAsyncWithHttpInfo
     *
     *
     *
     * @param  string $bible_id Id of Bible for passage (required)
     * @param  string $verse_id String reference id for the requested verse. (required)
     * @param  string $content_type Content type to be returned in the content property.  Supported values are &#x60;html&#x60; (default), &#x60;json&#x60; (beta), and &#x60;text&#x60; (beta) (optional, default to html)
     * @param  bool $include_notes Include footnotes in content (optional, default to false)
     * @param  bool $include_titles Include section titles in content (optional, default to true)
     * @param  bool $include_chapter_numbers Include chapter numbers in content (optional, default to false)
     * @param  bool $include_verse_numbers Include verse numbers in content. (optional, default to true)
     * @param  bool $include_verse_spans Include spans that wrap verse numbers and verse text for bible content. (optional, default to false)
     * @param  string $parallels Comma delimited list of bibleIds to include (optional)
     * @param  bool $use_org_id Use the supplied id(s) to match the verseOrgId instead of the verseId (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVerseAsyncWithHttpInfo($bible_id, $verse_id, $content_type = 'html', $include_notes = 'false', $include_titles = 'true', $include_chapter_numbers = 'false', $include_verse_numbers = 'true', $include_verse_spans = 'false', $parallels = null, $use_org_id = 'false')
    {
        $returnType = '\App\Clients\BibleClient\Model\InlineResponse20010';
        $request = $this->getVerseRequest($bible_id, $verse_id, $content_type, $include_notes, $include_titles, $include_chapter_numbers, $include_verse_numbers, $include_verse_spans, $parallels, $use_org_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getVerse'
     *
     * @param  string $bible_id Id of Bible for passage (required)
     * @param  string $verse_id String reference id for the requested verse. (required)
     * @param  string $content_type Content type to be returned in the content property.  Supported values are &#x60;html&#x60; (default), &#x60;json&#x60; (beta), and &#x60;text&#x60; (beta) (optional, default to html)
     * @param  bool $include_notes Include footnotes in content (optional, default to false)
     * @param  bool $include_titles Include section titles in content (optional, default to true)
     * @param  bool $include_chapter_numbers Include chapter numbers in content (optional, default to false)
     * @param  bool $include_verse_numbers Include verse numbers in content. (optional, default to true)
     * @param  bool $include_verse_spans Include spans that wrap verse numbers and verse text for bible content. (optional, default to false)
     * @param  string $parallels Comma delimited list of bibleIds to include (optional)
     * @param  bool $use_org_id Use the supplied id(s) to match the verseOrgId instead of the verseId (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getVerseRequest($bible_id, $verse_id, $content_type = 'html', $include_notes = 'false', $include_titles = 'true', $include_chapter_numbers = 'false', $include_verse_numbers = 'true', $include_verse_spans = 'false', $parallels = null, $use_org_id = 'false')
    {
        // verify the required parameter 'bible_id' is set
        if ($bible_id === null || (is_array($bible_id) && count($bible_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bible_id when calling getVerse'
            );
        }
        // verify the required parameter 'verse_id' is set
        if ($verse_id === null || (is_array($verse_id) && count($verse_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $verse_id when calling getVerse'
            );
        }

        $resourcePath = '/v1/bibles/{bibleId}/verses/{verseId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($content_type !== null) {
            $queryParams['content-type'] = ObjectSerializer::toQueryValue($content_type);
        }
        // query params
        if ($include_notes !== null) {
            $queryParams['include-notes'] = ObjectSerializer::toQueryValue($include_notes);
        }
        // query params
        if ($include_titles !== null) {
            $queryParams['include-titles'] = ObjectSerializer::toQueryValue($include_titles);
        }
        // query params
        if ($include_chapter_numbers !== null) {
            $queryParams['include-chapter-numbers'] = ObjectSerializer::toQueryValue($include_chapter_numbers);
        }
        // query params
        if ($include_verse_numbers !== null) {
            $queryParams['include-verse-numbers'] = ObjectSerializer::toQueryValue($include_verse_numbers);
        }
        // query params
        if ($include_verse_spans !== null) {
            $queryParams['include-verse-spans'] = ObjectSerializer::toQueryValue($include_verse_spans);
        }
        // query params
        if ($parallels !== null) {
            $queryParams['parallels'] = ObjectSerializer::toQueryValue($parallels);
        }
        // query params
        if ($use_org_id !== null) {
            $queryParams['use-org-id'] = ObjectSerializer::toQueryValue($use_org_id);
        }

        // path params
        if ($bible_id !== null) {
            $resourcePath = str_replace(
                '{' . 'bibleId' . '}',
                ObjectSerializer::toPathValue($bible_id),
                $resourcePath
            );
        }
        // path params
        if ($verse_id !== null) {
            $resourcePath = str_replace(
                '{' . 'verseId' . '}',
                ObjectSerializer::toPathValue($verse_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $headers['api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getVerses
     *
     * @param  string $bible_id Id of Bible whose Verses to fetch (required)
     * @param  string $chapter_id Id of the Chapter whose Verses to fetch (required)
     *
     * @throws \App\Clients\BibleClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \App\Clients\BibleClient\Model\InlineResponse2009
     */
    public function getVerses($bible_id, $chapter_id)
    {
        list($response) = $this->getVersesWithHttpInfo($bible_id, $chapter_id);
        return $response;
    }

    /**
     * Operation getVersesWithHttpInfo
     *
     * @param  string $bible_id Id of Bible whose Verses to fetch (required)
     * @param  string $chapter_id Id of the Chapter whose Verses to fetch (required)
     *
     * @throws \App\Clients\BibleClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \App\Clients\BibleClient\Model\InlineResponse2009, HTTP status code, HTTP response headers (array of strings)
     */
    public function getVersesWithHttpInfo($bible_id, $chapter_id)
    {
        $returnType = '\App\Clients\BibleClient\Model\InlineResponse2009';
        $request = $this->getVersesRequest($bible_id, $chapter_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\Clients\BibleClient\Model\InlineResponse2009',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getVersesAsync
     *
     *
     *
     * @param  string $bible_id Id of Bible whose Verses to fetch (required)
     * @param  string $chapter_id Id of the Chapter whose Verses to fetch (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVersesAsync($bible_id, $chapter_id)
    {
        return $this->getVersesAsyncWithHttpInfo($bible_id, $chapter_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getVersesAsyncWithHttpInfo
     *
     *
     *
     * @param  string $bible_id Id of Bible whose Verses to fetch (required)
     * @param  string $chapter_id Id of the Chapter whose Verses to fetch (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVersesAsyncWithHttpInfo($bible_id, $chapter_id)
    {
        $returnType = '\App\Clients\BibleClient\Model\InlineResponse2009';
        $request = $this->getVersesRequest($bible_id, $chapter_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getVerses'
     *
     * @param  string $bible_id Id of Bible whose Verses to fetch (required)
     * @param  string $chapter_id Id of the Chapter whose Verses to fetch (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getVersesRequest($bible_id, $chapter_id)
    {
        // verify the required parameter 'bible_id' is set
        if ($bible_id === null || (is_array($bible_id) && count($bible_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bible_id when calling getVerses'
            );
        }
        // verify the required parameter 'chapter_id' is set
        if ($chapter_id === null || (is_array($chapter_id) && count($chapter_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chapter_id when calling getVerses'
            );
        }

        $resourcePath = '/v1/bibles/{bibleId}/chapters/{chapterId}/verses';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($bible_id !== null) {
            $resourcePath = str_replace(
                '{' . 'bibleId' . '}',
                ObjectSerializer::toPathValue($bible_id),
                $resourcePath
            );
        }
        // path params
        if ($chapter_id !== null) {
            $resourcePath = str_replace(
                '{' . 'chapterId' . '}',
                ObjectSerializer::toPathValue($chapter_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $headers['api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
