<?php
/**
 * Meta
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API.Bible
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Clients\BibleClient\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Meta Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Meta implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Meta';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'fums' => 'string',
        'fums_id' => 'string',
        'fums_js_include' => 'string',
        'fums_js' => 'string',
        'fums_no_script' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'fums' => null,
        'fums_id' => null,
        'fums_js_include' => null,
        'fums_js' => null,
        'fums_no_script' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fums' => 'fums',
        'fums_id' => 'fumsId',
        'fums_js_include' => 'fumsJsInclude',
        'fums_js' => 'fumsJs',
        'fums_no_script' => 'fumsNoScript'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fums' => 'setFums',
        'fums_id' => 'setFumsId',
        'fums_js_include' => 'setFumsJsInclude',
        'fums_js' => 'setFumsJs',
        'fums_no_script' => 'setFumsNoScript'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fums' => 'getFums',
        'fums_id' => 'getFumsId',
        'fums_js_include' => 'getFumsJsInclude',
        'fums_js' => 'getFumsJs',
        'fums_no_script' => 'getFumsNoScript'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['fums'] = isset($data['fums']) ? $data['fums'] : null;
        $this->container['fums_id'] = isset($data['fums_id']) ? $data['fums_id'] : null;
        $this->container['fums_js_include'] = isset($data['fums_js_include']) ? $data['fums_js_include'] : null;
        $this->container['fums_js'] = isset($data['fums_js']) ? $data['fums_js'] : null;
        $this->container['fums_no_script'] = isset($data['fums_no_script']) ? $data['fums_no_script'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['fums'] === null) {
            $invalidProperties[] = "'fums' can't be null";
        }
        if ($this->container['fums_id'] === null) {
            $invalidProperties[] = "'fums_id' can't be null";
        }
        if ($this->container['fums_js_include'] === null) {
            $invalidProperties[] = "'fums_js_include' can't be null";
        }
        if ($this->container['fums_js'] === null) {
            $invalidProperties[] = "'fums_js' can't be null";
        }
        if ($this->container['fums_no_script'] === null) {
            $invalidProperties[] = "'fums_no_script' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fums
     *
     * @return string
     */
    public function getFums()
    {
        return $this->container['fums'];
    }

    /**
     * Sets fums
     *
     * @param string $fums fums
     *
     * @return $this
     */
    public function setFums($fums)
    {
        $this->container['fums'] = $fums;

        return $this;
    }

    /**
     * Gets fums_id
     *
     * @return string
     */
    public function getFumsId()
    {
        return $this->container['fums_id'];
    }

    /**
     * Sets fums_id
     *
     * @param string $fums_id fums_id
     *
     * @return $this
     */
    public function setFumsId($fums_id)
    {
        $this->container['fums_id'] = $fums_id;

        return $this;
    }

    /**
     * Gets fums_js_include
     *
     * @return string
     */
    public function getFumsJsInclude()
    {
        return $this->container['fums_js_include'];
    }

    /**
     * Sets fums_js_include
     *
     * @param string $fums_js_include fums_js_include
     *
     * @return $this
     */
    public function setFumsJsInclude($fums_js_include)
    {
        $this->container['fums_js_include'] = $fums_js_include;

        return $this;
    }

    /**
     * Gets fums_js
     *
     * @return string
     */
    public function getFumsJs()
    {
        return $this->container['fums_js'];
    }

    /**
     * Sets fums_js
     *
     * @param string $fums_js fums_js
     *
     * @return $this
     */
    public function setFumsJs($fums_js)
    {
        $this->container['fums_js'] = $fums_js;

        return $this;
    }

    /**
     * Gets fums_no_script
     *
     * @return string
     */
    public function getFumsNoScript()
    {
        return $this->container['fums_no_script'];
    }

    /**
     * Sets fums_no_script
     *
     * @param string $fums_no_script fums_no_script
     *
     * @return $this
     */
    public function setFumsNoScript($fums_no_script)
    {
        $this->container['fums_no_script'] = $fums_no_script;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


